dotnet_6:
  # Use .NET SDK from Microsoft Container Registry.
  image: mcr.microsoft.com/dotnet/sdk:6.0
  stage: build
  before_script:
    - dotnet --info
  script:
    - dotnet build msi-info/msi-info.sln

dotnet_7:
  # Use .NET SDK from Microsoft Container Registry.
  image: mcr.microsoft.com/dotnet/sdk:7.0
  stage: build
  before_script:
    - dotnet --info
  script:
    - dotnet build msi-info/msi-info.sln
